name: ibd-cdi
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-base=4
  - r-cowplot
  - r-data.table
  - r-doFuture
  - r-foreach
  - r-future
  - r-future.apply
  - r-ggtext
  - r-here
  - r-mikropml>1.2.2
  - r-patchwork
  - r-rmarkdown
  - r-rpart
  - r-schtools
  - r-tidyverse
  - snakemake
